[tool.poetry]
name = "analsis-recipes"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.1.3"
jupyter = "^1.1.1"
cas-visualizer = "^0.0.9"
dakoda-core = {path = "../dakoda-core/"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = [
  "."
]